# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"

before_install:
  - pip install coveralls
  #- pip install python-coveralls

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  #- py.test
  - coverage run --source=dolphin setup.py test

after_success:
    coveralls