# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
  - "3.6"
  - "2.7.16"

before_install:
  - pip install coveralls
  - pip install tox-travis
  #- pip install python-coveralls

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install pluggy==0.13.0
  - pip install -U pytest
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  #- py.test
  #- coverage run --source=dolphin setup.py test
  - tox

after_success:
    coveralls